language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage --cover-package=wordlist
after_success:
  - coveralls
